article:
  type: tech
  auto_excerpt: 200
  related_posts:
    enable: true
    title: 您可能感兴趣的文章
  license: '本文由 <a href="{author.url}">{author.name}</a> 编写，请你在改编、转载时注明出处，谢谢喵~'
  share: [wechat, weibo, email, link]
logo:
  subtitle: '稚梦 · 随意写，随意看 | 我是爷们！'
menubar:
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
   - id: post # 页面中高亮的 menu_id
     theme: '#1BCDFC' # 激活/悬停时的主题色，图标与圆点会以该颜色生成渐变
     icon: solar:documents-bold-duotone # 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
     title: blog # 标题
     url: / # 跳转链接，支持相对路径和绝对路径
   - id: wiki
     theme: '#3DC550'
     icon: solar:notebook-bookmark-bold-duotone
     title: XTC Root Helper
     url: /wiki/
   - id: notebooks
     theme: '#FA6400'
     icon: solar:planet-bold-duotone
     title: 探索
     url: /notes/
   - id: about
     theme: '#F44336'
     icon: solar:atom-bold-duotone
     title: 关于
     url: /about/introduction/

site_tree:
  notebooks:
    base_dir: notes # 笔记本列表页路径，改为 /notes/
  author:
    base_dir: about

search:
  service: local_search
  local_search:
    field: all
    path: /search.json
    content: true
    skip_search: []
    codeblock: true

comments:
  service: giscus
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    src: https://giscus.app/client.js
    data-repo: Mengmiya1027/ZMdocs # [在此输入仓库]
    data-repo-id: R_kgDOTlCvAA # [在此输入仓库 ID]
    data-category: Announcements # [在此输入分类名]
    data-category-id: DIC_kwDOTlCvAM4DDNw1
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: noborder_light
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous

style:
  font-family:
    body: '"LXGW WenKai",sans-serif'
  leftbar:
    ui-style: glass

copycode:
  enable: true
  js: /js/plugins/copycode.js
  default_text: '复制' # 按钮显示文字
  success_text: '已经复制啦~' # 复制成功信息

dependencies:
  lazyload:
    js: https://gcore.jsdelivr.net/npm/vanilla-lazyload@19.1/dist/lazyload.min.js
    transition: fade # blur, fade
    fix_ratio: true # true / false

# 默认打开
loading:
  loading: 加载中……请稍后~
  error: 加载失败T^T


footer:
  social:
    github:
      icon: line-md:github
      url: https://github.com/Mengmiya1027/ZMdocs-plus
    music:
      icon: mingcute:qq-line
      url: https://qm.qq.com/q/cbQklVGWB2
    unsplash:
      icon: '<img src="https://www.alltoolbox.app/logo.png"/>'
      url: https://www.alltoolbox.app/
    comments:
      icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder/social/942ebbf1a4b91.svg"/>'
      url: https://qm.qq.com/q/Y1Ix4uSE0K
  sitemap:
    - title: 站点地图
      items:
        - '[近期发布](/)'
        - '[XTC Root Helper](/wiki/)'
    - title: 链接
      items:
        - '[ZMdocs-plus仓库](https://github.com/Mengmiya1027/ZMdocs-plus)'
        - '[稚梦沈星河](https://github.com/SB5133)'
        - '[愿Wish](https://github.com/Mengmiya1027)'
        - '[AllToolBox](https://www.alltoolbox.app/)'
  content: | # 支持 Markdown 格式
    <script src="//cdn.busuanzi.cc/busuanzi/3.6.9/busuanzi.min.js" defer></script>
    感谢 <span id="busuanzi_site_uv">Loading...</span> 个小伙伴的第 <span id="busuanzi_site_pv">Loading...</span> 次光临本站！
    本站总访问量 <span id="busuanzi_site_pv">加载中...</span> 次 
    本站由 **[{author.name}](/)** 创建。
    本博客所有文章除特别声明外，均采用 **[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)** 许可协议，**转载请注明出处**。
    **每日一言**：<span class="jinrishici-sentence"></span>
    <script src="https://sdk.jinrishici.com/v2/browser/jinrishici.js" charset="utf-8"></script>

# 让左侧栏 linklist 组件（如探索导航）左对齐
inject:
  head:
    - |
      <style>
      .widget-wrapper.linklist .linklist .link {
        justify-content: space-between;
        padding: 0 16px;
      }
      </style>
